version: "2"

services:
  jobmanager:
    image: laus.fzi.de:8201/streampipes/flink
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - /home/riemer/swarm/config/flink:/opt/flink/conf

  taskmanager:
    image: laus.fzi.de:8201/streampipes/flink
    command: taskmanager
    volumes:
      - /home/riemer/swarm/config/flink:/opt/flink/conf
