apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: consul
spec:
  selector:
    matchLabels:
      app: consul
  replicas: 1
  template:
    metadata:
      labels:
        app: consul
    spec:
      volumes:
        - name: consul-pv
          persistentVolumeClaim:
            claimName: consul-pvc
      containers:
        - name: consul
          image: consul
          ports:
            - containerPort: 8500
            - containerPort: 8600
          volumeMounts:
            - mountPath: "/consul/data"
              name: consul-pv