elasticsearch:
   image: elasticsearch:2.4.1
   net: "host"
   ports:
       - "9200:9200"
       - "9300:9300"
   volumes:
       - ./config/elasticsearch/data:/usr/share/elasticsearch/data
       - ./config/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
kibana:
   image: kibana:4.6.1
   net: "host"
   ports:
       - "5601:5601"
   volumes:
       - ./config/kibana/kibana.yml:/opt/kibana/config/kibana.yml
