version: "2"
services:
  couchdb:
    image: couchdb:2.1.1
    ports:
      - "5984:5984"
    volumes:
       - couchdb:/opt/couchdb/data
    networks:
      spnet:

volumes:
  couchdb:

networks:
  spnet:
    external: true
