apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: init-wait-consul
          image: alpine
          command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 consul 8600 && exit 0 || sleep 3; done; exit 1"]
        - name: init-wait-couchdb
          image: alpine
          command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 couchdb 5984 && exit 0 || sleep 3; done; exit 1"]
      volumes:
        - name: backend-pv
          persistentVolumeClaim:
            claimName: backend-pvc
      containers:
        - name: backend
          image: {{ .Values.streampipes.registry }}/backend:{{ .Values.streampipes.version }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - containerPort: 8030
          volumeMounts:
            - mountPath: "/root/.streampipes"
              name: backend-pv
      imagePullSecrets:
        - name: gitlab-registry
