apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: couchdb
spec:
  selector:
    matchLabels:
      app: couchdb
  replicas: 1
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      volumes:
        - name: couchdb-pv
          persistentVolumeClaim:
            claimName: couchdb-pvc
      containers:
        - name: couchdb
          image: couchdb:2.1.1
          ports:
            - containerPort: 5984
          volumeMounts:
            - mountPath: "/opt/couchdb/data"
              name: couchdb-pv