variables:
  REGISTRY_HOST: ipe-wim-gitlab.fzi.de:5000
  IMAGE_NAME: $REGISTRY_HOST/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME

stages:
   - build
   - docker
   - docker-hub

build:
  image: beevelop/nodejs-python
  stage: build
  script:
    - export NODE_PATH=/cache/node_modules
    - npm install --unsafe-perm
    - npm run build
  artifacts:
    paths:
      - dist/assets/css/
      - dist/assets/img/
      - dist/assets/lib/
      - dist/assets/templates/
      - dist/index.html
      - dist/main.bundle.js
      - dist/polyfills.bundle.js
      - dist/style.bundle.css
    expire_in: 1 hour

nginx:
  image: docker:17.06.0-ce
  stage: docker
  script:
    - apk update
    - apk add curl
    - apk add unzip
    - 'curl -k -f -L -H "PRIVATE-TOKEN: ${API_KEY}" -o docs.zip "https://ipe-wim-gitlab.fzi.de/streampipes/docs/-/jobs/artifacts/master/download?job=build"'
    - unzip docs.zip
    - 'curl -k -f -L -H "PRIVATE-TOKEN: ${API_KEY}" -o javadoc.zip "https://ipe-wim-gitlab.fzi.de/streampipes/ce/-/jobs/artifacts/dev/download?job=build"'
    - unzip javadoc.zip
    - mkdir javadoc && mv target/site/apidocs/* ./javadoc
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY_HOST
    - docker build --pull -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

nginx-docker-hub:
  image: docker:17.06.0-ce
  stage: docker-hub
  script:
    - apk update
    - apk add curl
    - apk add unzip
    - 'curl -k -f -L -H "PRIVATE-TOKEN: ${API_KEY}" -o docs.zip "https://ipe-wim-gitlab.fzi.de/streampipes/docs/-/jobs/artifacts/master/download?job=build"'
    - unzip docs.zip
    - mkdir javadoc
    - docker login -u streampipesbuild -p $DOCKER_HUB_USER_PWD
    - docker build --pull -t streampipes/ui:$CI_COMMIT_REF_NAME .
    - docker push streampipes/ui:$CI_COMMIT_REF_NAME
    - docker build --pull -t streampipes/ui .
    - docker push streampipes/ui
  when: manual
  only:
    - 0.5.0
    
nginx-testfeld:
  image: docker:17.06.0-ce
  stage: docker
  script:
    - apk update
    - apk add curl
    - apk add unzip
    - 'curl -k -f -L -H "PRIVATE-TOKEN: ${API_KEY}" -o docs.zip "https://ipe-wim-gitlab.fzi.de/streampipes/docs/-/jobs/artifacts/master/download?job=build"'
    - unzip docs.zip
    - mkdir javadoc
    - docker login -u riemer -p $HARBOR_PASSWORD laus.fzi.de:8201
    - docker build --pull -t laus.fzi.de:8201/testfeld/ui:$CI_COMMIT_REF_NAME .
    - docker push laus.fzi.de:8201/testfeld/ui:$CI_COMMIT_REF_NAME
  only:
    - testfeld

