variables:
  REGISTRY_HOST: ipe-wim-gitlab.fzi.de:5000
  IMAGE_NAME: $REGISTRY_HOST/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME

stages:
   - build
   - docker

build:
  image: beevelop/nodejs-python
  stage: build
  script:
    - export NODE_PATH=/cache/node_modules
    - npm install --unsafe-perm
    - npm run dev-build
  artifacts:
    paths:
      - img/
      - css/
      - index.html
      - bundle.js
      - app/**/*.html
      - templates/**/*.html
    expire_in: 1 hour

nginx:
  image: docker:17.06.0-ce
  stage: docker
  script:
    - apk update
    - apk add curl
    - apk add unzip
    - 'curl -k -f -L -H "PRIVATE-TOKEN: ${API_KEY}" -o docs.zip "https://ipe-wim-gitlab.fzi.de/streampipes/docs/-/jobs/artifacts/master/download?job=build"'
    - unzip docs.zip
    - 'curl -k -f -L -H "PRIVATE-TOKEN: ${API_KEY}" -o javadoc.zip "https://ipe-wim-gitlab.fzi.de/streampipes/ce/-/jobs/artifacts/dev/download?job=build"'
    - unzip javadoc.zip
    - rm javadoc.zip
    - rm -rf javadoc/streampipes-backend && rm -rf javadoc/streampipes-pe-mixed && rm -rf javadoc/streampipes-pe-processors-esper && rm -rf javadoc/streampipes-pe-sinks-standlone && rm -rf javadoc/streampipes-pe-sources-axoom-hmi && rm -rf javadoc/streampipes-pe-sources-mnist && rm -rf javadoc/streampipes-pe-sources-samples
    - cd javadoc && mv target/site/apidocs ./
    - rm -rf target
    - ls -la
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY_HOST
    - docker build --pull -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
    - rm docs.zip
    - rm -rf site/

