variables:
  REGISTRY_HOST: ipe-wim-gitlab.fzi.de:5000
  HARBOR_REGISTRY_HOST: laus.fzi.de:8201
  HARBOR_IMAGE_NAME: $HARBOR_REGISTRY_HOST/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME
  IMAGE_NAME: $REGISTRY_HOST/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME

stages:
   - build
   - docker
   - docker-hub

#test:
#  image: beevelop/nodejs-python
#  stage: test
#  script:
#    - apt-get update && apt-get install -y apt-transport-https ca-certificates
#    - curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
#    - echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
#    - apt-get update
#    - apt-get install -y google-chrome-stable --no-install-recommends
#    - apt-get install -y firefox --no-install-recommends
#    - export CHROME_BIN=google-chrome
#    - export NODE_PATH=/cache/node_modules
#    - npm install --unsafe-perm
#    - npm test

build:
  image: beevelop/nodejs-python
  stage: build
  script:
    - export NODE_PATH=/cache/node_modules
    - npm install --unsafe-perm
    - npm run build
  artifacts:
    paths:
      - dist/assets/css/
      - dist/assets/img/
      - dist/assets/lib/
      - dist/assets/templates/
      - dist/assets/fonts/
      - dist/index.html
      - dist/main.bundle.js
      - dist/polyfills.bundle.js
      - dist/style.bundle.css
      - dist/runtime.bundle.js
      - dist/style.bundle.js
      - dist/style.css
    expire_in: 1 hour

nginx:
  image: docker:17.06.0-ce
  stage: docker
  script:
    - apk update
    - apk add curl
    - apk add unzip
#    - 'curl -k -f -L -H "PRIVATE-TOKEN: ${API_KEY}" -o javadoc.zip "https://ipe-wim-gitlab.fzi.de/streampipes/ce/-/jobs/artifacts/dev/download?job=build"'
#    - unzip javadoc.zip
#    - mkdir javadoc && mv target/site/apidocs/* ./javadoc
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY_HOST
    - docker login -u riemer -p $HARBOR_PASSWORD $HARBOR_REGISTRY_HOST
    - docker build --no-cache --pull -t $HARBOR_IMAGE_NAME -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
    - docker push $HARBOR_IMAGE_NAME

nginx-docker-hub:
  image: docker:17.06.0-ce
  stage: docker-hub
  script:
    - apk update
    - apk add curl
    - mkdir javadoc
    - docker login -u streampipesbuild -p $DOCKER_HUB_USER_PWD
    - docker build --pull -t streampipes/ui:$CI_COMMIT_REF_NAME .
    - docker push streampipes/ui:$CI_COMMIT_REF_NAME
    - docker build --pull -t streampipes/ui .
    - docker push streampipes/ui
  when: manual
  only:
    - 0.61.0
    
nginx-testfeld:
  image: docker:17.06.0-ce
  stage: docker
  script:
    - apk update
    - apk add curl
    - apk add unzip
    #- 'curl -k -f -L -H "PRIVATE-TOKEN: ${API_KEY}" -o docs.zip "https://ipe-wim-gitlab.fzi.de/streampipes/docs/-/jobs/artifacts/master/download?job=build"'
    #- unzip docs.zip
    #- mkdir javadoc
    - docker login -u riemer -p $HARBOR_PASSWORD laus.fzi.de:8201
    - docker build --pull -t laus.fzi.de:8201/testfeld/ui:$CI_COMMIT_REF_NAME .
    - docker push laus.fzi.de:8201/testfeld/ui:$CI_COMMIT_REF_NAME
  only:
    - testfeld

