variables:
  IMAGE_NAME: $REGISTRY_HOST/$CI_PROJECT_PATH
  DOCKER_HUB_IMAGE_NAME: streampipes
  MAVEN_CLI_OPTS: -DskipTests --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true
  HARBOR_IMAGE_NAME: $HARBOR_REGISTRY_HOST/$CI_PROJECT_PATH
  GIT_STRATEGY: clone


stages:
  - build
  - docker
  - deploy
  - release
  - docker-hub

build:
  image: maven:3.6.1-jdk-8
  stage: build
  script:
#    - echo "$GPG_PRIVATE_KEY" | gpg --batch --import --passphrase "$GPG_PASSPHRASE"
    - echo "$MAVEN_CREDENTIALS" > /root/.m2/settings.xml
    - mvn clean package javadoc:aggregate -U -DskipTests
    - export MVN_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\[')
    - "echo $MVN_VERSION >> ./target/mvn_version"
  artifacts:
    paths:
      - /release-.*$/
      - ./streampipes-connect-container/target/*.jar
      - ./*/target/*.jar
    expire_in:  1 hour
#  except:
#      - /release-.*$/
#      - ./*/target/*.jar
#      - ./target/mvn_version


docker-connect-container:
   image: docker:17.06.0-ce
   stage: docker
   dependencies:
     - build
   script:
#     - export MVN_VERSION=0.62.1-SNAPSHOT
     - export MVN_VERSION=$(cat ./target/mvn_version)
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY_HOST
     - docker login -u zehnder -p $HARBOR_PASSWORD ipe-harbor.fzi.de
     - docker build --pull -t $IMAGE_NAME/streampipes-connect-worker:latest -t $IMAGE_NAME/streampipes-connect-worker:$MVN_VERSION -t $HARBOR_IMAGE_NAME/streampipes-connect-worker:latest -t $HARBOR_IMAGE_NAME/streampipes-connect-worker:$MVN_VERSION ./streampipes-connect-adapter/
     - docker push $IMAGE_NAME/streampipes-connect-worker:$MVN_VERSION
     - docker push $IMAGE_NAME/streampipes-connect-worker:latest
     - docker push $HARBOR_IMAGE_NAME/streampipes-connect:$MVN_VERSION
     - docker push $HARBOR_IMAGE_NAME/streampipes-connect:latest
   only:
     - dev
