variables:
  REGISTRY_HOST: ipe-wim-gitlab.fzi.de:5000
  IMAGE_NAME: $REGISTRY_HOST/$CI_PROJECT_PATH

stages:
   - build
   - docker

build:
  image: beevelop/nodejs-python
  stage: build
  script:
    - npm install --unsafe-perm
    - npm run dev-build
  artifacts:
    paths:
      - img/**
      - css/**
      - index.html
      - bundle.js
      - app/**/*.html
      - templates/**/*.html
    expire_in: 1 hour

nginx:
  image: docker:17.06.0-ce
  stage: docker
  script:
    - ls 
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY_HOST
    - docker build --pull -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
