variables:
  REGISTRY_HOST: ipe-wim-gitlab.fzi.de:5000
  IMAGE_NAME: $REGISTRY_HOST/$CI_PROJECT_PATH
  MAVEN_CLI_OPTS: -DskipTests --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true

stages:
  - build
  - docker
  - deploy
  - release

build:
  image: maven:3-jdk-8
  stage: build
  script:
    - echo "$GPG_PRIVATE_KEY" | gpg --batch --import --passphrase "$GPG_PASSPHRASE"
    - echo "$MAVEN_CREDENTIALS" > /root/.m2/settings.xml
    - mvn clean package javadoc:aggregate -U -DskipTests
    - export MVN_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\[')
    - "echo $MVN_VERSION >> ./target/mvn_version"
  artifacts:
    paths:
      - ./*/target/*.jar
      - ./target/mvn_version
    expire_in:  1 hour
  except:
      - /release-.*$/

.docker_script: &docker_script
   image: docker:17.06.0-ce
   stage: docker
   dependencies:
     - build
   script:
     - export MVN_VERSION=$(cat ./target/mvn_version)
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY_HOST
     - docker build --no-cache --pull  -t $IMAGE_NAME/$CONTAINER_NAME:latest -t $IMAGE_NAME/$CONTAINER_NAME:$MVN_VERSION ./streampipes-$CONTAINER_NAME
     - docker push $IMAGE_NAME/$CONTAINER_NAME:$MVN_VERSION
     - docker push $IMAGE_NAME/$CONTAINER_NAME:latest
   only:
     - dev

deploy:
  image: maven:3-jdk-8
  stage: deploy
  script:
    - echo "$GPG_PRIVATE_KEY" | gpg --batch --import --passphrase "$GPG_PASSPHRASE"
    - echo "$MAVEN_CREDENTIALS" > /root/.m2/settings.xml
    - mvn deploy -DskipTests
  only:
    - dev

start release:
  image: maven:3-jdk-8
  stage: release
  script:
    - echo "$MAVEN_CREDENTIALS" > /root/.m2/settings.xml
    - git remote set-url origin $GIT_REPO_ORIGIN/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME.git
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH")
    - mkdir ~/.ssh
    - touch ~/.ssh/known_hosts
    - ssh-keyscan -p 2222 -t rsa ipe-wim-gitlab.fzi.de > ~/.ssh/known_hosts
    - git config --global user.email 'zehnder@fzi.de'
    - git config --global user.name 'zehnder'
    - git fetch
    - git checkout master
    - git checkout dev
    - mvn -B jgitflow:release-start $MAVEN_CLI_OPTS
    - git push origin --all
  only:
    - dev
  when: manual

finish release:
  image: maven:3-jdk-8
  stage: release
  script:
    - echo "$MAVEN_CREDENTIALS" > /root/.m2/settings.xml
    - git remote set-url origin $GIT_REPO_ORIGIN/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME.git
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH")
    - mkdir ~/.ssh
    - touch ~/.ssh/known_hosts
    - ssh-keyscan -p 2222 -t rsa ipe-wim-gitlab.fzi.de > ~/.ssh/known_hosts
    - git config --global user.email 'zehnder@fzi.de'
    - git config --global user.name 'zehnder'
    - git checkout master
    - git checkout dev
    - git checkout $CI_BUILD_REF_NAME
    - mvn -B jgitflow:release-finish $MAVEN_CLI_OPTS
    - git push origin --all
    - git push origin --tags
  when: manual
  except:
    - master

docker-processors-aggregation-flink:
    <<: *docker_script
    variables:
      CONTAINER_NAME: "processors-aggregation-flink"

docker-processors-enricher-flink:
    <<: *docker_script
    variables:
      CONTAINER_NAME: "processors-enricher-flink"

docker-processors-filters-jvm:
    <<: *docker_script
    variables:
      CONTAINER_NAME: "processors-filters-jvm"

docker-processors-geo-jvm:
    <<: *docker_script
    variables:
      CONTAINER_NAME: "processors-geo-jvm"

docker-processors-pattern-detection-flink:
    <<: *docker_script
    variables:
      CONTAINER_NAME: "processors-pattern-detection-flink"

docker-processors-siddhi:
    <<: *docker_script
    variables:
      CONTAINER_NAME: "processors-siddhi"

docker-processors-statistics-flink:
    <<: *docker_script
    variables:
      CONTAINER_NAME: "processors-statistics-flink"

docker-processors-transformation-flink:
    <<: *docker_script
    variables:
      CONTAINER_NAME: "processors-transformation-flink"

docker-sinks-brokers-jvm:
    <<: *docker_script
    variables:
      CONTAINER_NAME: "sinks-brokers-jvm"

docker-sinks-databases-flink:
    <<: *docker_script
    variables:
      CONTAINER_NAME: "sinks-databases-flink"

docker-sinks-databases-jvm:
    <<: *docker_script
    variables:
      CONTAINER_NAME: "sinks-databases-jvm"

docker-sinks-internal-jvm:
    <<: *docker_script
    variables:
      CONTAINER_NAME: "sinks-internal-jvm"

docker-sources-vehicle-simulator:
    <<: *docker_script
    variables:
      CONTAINER_NAME: "sources-vehicle-simulator"

docker-sources-:
    <<: *docker_script
    variables:
      CONTAINER_NAME: "sources-watertank-simulator"

