stages:
   - build

build:
  image: beevelop/nodejs-python
  stage: build
  script:
    - npm install --unsafe-perm
    - npm run dev-build
  artifacts:
    - img/**
    - css/**
    - index.html
    - bundle.js
    - app/**/*.html
    - templates/**/*.html
  expire_in: 1 hour
