apiVersion: v1
appVersion: "0.65.0"
description: Self-Service Data Analytics for the Industrial IoT
name: streampipes-helm-chart
home: https://streampipes.org
version: 0.65.0
icon: https://avatars1.githubusercontent.com/u/33908576
maintainers:
  - name: Dominik Riemer
    email: riemer@fzi.de
  - name: Philipp Zehnder
    email: zehnder@fzi.de
  - name: Samuel Abt
    email: abt@fzi.de
  - name: Patrick Wiener
    email: wiener@fzi.de
