version: "2"
services:
  connect-worker-main:
    image: ${SP_DOCKER_REGISTRY}streampipes/streampipes-connect-adapters/streampipes-connect-worker:${SP_BACKEND_VERSION}
    depends_on:
      - consul
      - couchdb
    ports:
      - "8098:8098"
    environment:
      - SP_CONNECT_CONTAINER_HOST=connect-master
      - SP_CONNECT_CONTAINER_WORKER=connect-worker-main
      - SP_KAFKA_HOST=${SP_KAFKA_HOST}
    volumes:
      - connect:/data/
    networks:
      spnet:

volumes:
  connect:

networks:
  spnet:
    external: true
