{{- if eq .Values.deployment "full" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager
spec:
  selector:
    matchLabels:
      app: taskmanager
  replicas: 1
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      containers:
        - name: taskmanager
          image: "flink:{{ .Values.external.flinkVersion }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          args: ["taskmanager"]
          ports:
            - containerPort: 8099
          env:
            - name: TASK_MANAGER_NUMBER_OF_TASK_SLOTS
              value: "20"
            - name: JOB_MANAGER_RPC_ADDRESS
              value: jobmanager
{{- end }}
