{{- if eq .Values.deployment "full" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iotdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{{- end}}
