version: "2"
services:
  backend:
    image: ${SP_DOCKER_REGISTRY}streampipes/ce/backend:${SP_BACKEND_VERSION}
    depends_on:
      - consul
      - couchdb
    ports:
      - "8030:8030"
    environment:
      - SP_KAFKA_HOST=${SP_KAFKA_HOST}
    volumes:
      - backend:/root/.streampipes
    networks:
      spnet:

volumes:
  backend:

networks:
  spnet:
    external: true
