version: "2"
services:
  processors-text-mining-jvm:
    image: ${SP_PE_DOCKER_REGISTRY}processors-text-mining-jvm:${SP_PE_VERSION}
    depends_on:
      - "consul"
    volumes:
      - "config":"/data/models/"
    environment:
      - SP_ICON_HOST=${SP_ICON_HOST}
      - SP_KAFKA_HOST=${SP_KAFKA_HOST}
    networks:
      spnet:

networks:
  spnet:
    external: true