version: "2"
services:
  connect-master:
    image: ${SP_DOCKER_REGISTRY}/streampipes/ce/streampipes-connect-container:${SP_BACKEND_VERSION}
    depends_on:
      - consul
      - couchdb
    ports:
      - "8099:8099"
    environment:
      - EXECUTION_MODE=MASTER
      - SP_CONNECT_CONTAINER_HOST=connect-master      
      - SP_CONNECT_CONTAINER_WORKER=connect-worker
    networks:
      spnet:

