version: "2"
services:
  activemq:
    image: streampipes/activemq:5.15.9
    ports:
      - "61616:61616"
      - "61614:61614"
      - "8161:8161"
      - "1883:1883"
    networks:
      spnet:

networks:
  spnet:
    external: true
