version: "2"
services:
  nginx:
    image: ${SP_DOCKER_REGISTRY}/streampipes/ui:0.55.2
    ports:
      - "80:80"
    depends_on:
      - couchdb
      - activemq
      - consul
      - swagger-ui
    networks:
      spnet:
 
