version: "2"
services:
  nginx:
    image: streampipes/ui:0.55.2
    ports:
      - "80:80"
    depends_on:
      - backend
      - couchdb
      - activemq
      - consul
    networks:
      spnet:
 
