apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect-master
spec:
  selector:
    matchLabels:
      app: connect-master
  replicas: 1
  template:
    metadata:
      labels:
        app: connect-master
    spec:
      initContainers:
        - name: init-wait-consul
          image: alpine
          command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 consul 8600 && exit 0 || sleep 3; done; exit 1"]
        - name: init-wait-couchdb
          image: alpine
          command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 couchdb 5984 && exit 0 || sleep 3; done; exit 1"]
      containers:
        - name: connect-master
          image: {{ .Values.streampipes.registry }}/streampipes-connect-container:{{ .Values.streampipes.version }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: EXECUTION_MODE
              value: MASTER
            - name: SP_CONNECT_CONTAINER_MASTER_HOST
              value: connect-master
            - name: SP_KAFKA_HOST
              value: kafka
          ports:
            - containerPort: 8099
      imagePullSecrets:
        - name: gitlab-registry
