version: "2"
services:
  taskmanager:
    image: streampipes/flink:1.4
    command: taskmanager
    environment:
      - FLINK_NUM_SLOTS=20
    networks:
      spnet:

networks:
  spnet:
    external: true
