version: "2"
services:
  sinks-internal-production:
    image: ${SP_INTERNAL_PE_DOCKER_REGISTRY}/sinks-internal-production:${SP_PE_VERSION}
    depends_on:
      - "consul"
#    ports:
#      - "8098:8090"
    environment:
      - SP_ICON_HOST=${SP_ICON_HOST}
    networks:
      spnet:

