version: "2"
services:
  sources-watertank-simulator:
    image: ${SP_PE_DOCKER_REGISTRY}sources-watertank-simulator:${SP_PE_VERSION}
    depends_on:
      - "consul"
#    ports:
#      - "8098:8090"
    environment:
      - SP_ICON_HOST=${SP_ICON_HOST}
      - SP_KAFKA_HOST=kafka
    networks:
      spnet:

networks:
  spnet:
    external: true
