apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: "streampipes/ui:{{ .Values.streampipesVersion }}"
          ports:
            - containerPort: 80
        # This is necessary because a custom dns resolver is set in nginx default conf
        - name: dnsmasq
          image: janeczku/go-dnsmasq:release-1.0.7
          args:
            - --listen
            - "127.0.0.11:53"
            - --default-resolver
            - --append-search-domains
            - --hostsfile=/etc/hosts
            - --verbose