version: "2"
services:
  logstash:
    image: ${SP_DOCKER_REGISTRY}streampipes/services/logstash
    depends_on:
      - kafka
    ports:
      - "5044:5044"
    networks:
      spnet:

networks:
  spnet:
    external: true
