version: "2.0"
services:
  mariadb:
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user1
      MYSQL_PASSWORD: 9N28_b2uhj./x-Vm
      MYSQL_ROOT_PASSWORD: uJ-ft,2CX7YD8N,P
    networks:
      spnet:

volumes:
  mariadb

networks:
  spnet:
    external: true
