apiVersion: v1
kind: Service
metadata:
  name: activemq
spec:
  selector:
    app: activemq
  type: NodePort
  ports:
    - name: main
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: websocket
      protocol: TCP
      port: 61614
      targetPort: 61614
    - name: ui
      protocol: TCP
      port: 8161
      targetPort: 8161
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883