apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: connect-worker
spec:
  selector:
    matchLabels:
      app: connect-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: connect-worker
    spec:
      initContainers:
        - name: init-wait-consul
          image: alpine
          command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 consul 8600 && exit 0 || sleep 3; done; exit 1"]
        - name: init-wait-couchdb
          image: alpine
          command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 couchdb 5984 && exit 0 || sleep 3; done; exit 1"]
      containers:
        - name: connect-worker
          image: "streampipes/streampipes-connect-container:{{ .Values.streampipesVersion }}"
          env:
            - name: EXECUTION_MODE
              value: "WORKER"
            - name: SP_CONNECT_CONTAINER_HOST
              value: "connect-master"
            - name: SP_CONNECT_CONTAINER_WORKER
              value: "connect-worker"
            - name: SP_KAFKA_HOST
              value: "kafka-service"

          ports:
            - containerPort: 8099
