apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  selector:
    app: consul
  type: NodePort
  ports:
    - name: main
      protocol: TCP
      port: 8500
      targetPort: 8500
    - name: test
      protocol: TCP
      port: 8600
      targetPort: 8600