version: "2"
services:
  kafka-rest:
    image: confluentinc/cp-kafka-rest
    ports:
      - "8073:8082"
    depends_on:
      - zookeeper
    environment:
      - ZK_CONNECTION_STRING=zookeeper:2181
      - KAFKA_REST_HOST_NAME=${SP_HOST}
      - KAFKA_REST_ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      spnet:

networks:
  spnet:
    external: true
