{{- if eq .Values.deployment "full" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      volumes:
        - name: influxdb-pv
          persistentVolumeClaim:
            claimName: influxdb-pvc
      containers:
        - name: influxdb
          image: influxdb:{{ .Values.external.influxdbVersion }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - containerPort: 8083
            - containerPort: 8086
            - containerPort: 8090
          env:
            - name: INFLUXDB_DATA_ENGINE
              value: tsm1
            - name: INFLUXDB_REPORTING_DISABLED
              value: false
            - name: INFLUXDB_ADMIN_ENABLED
              value: true
          volumeMounts:
            - mountPath: "/var/lib/influxdb"
              name: influxdb-pv
{{- end }}
