version: "2"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 141.21.9.88
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    image: laus.fzi.de:8201/streampipes/semantic-epa-backend
#    ports:
#      - "8030:8030"
    volumes:
      - /home/riemer/swarm/config:/root/.streampipes
      - /home/riemer/swarm/config/aduna:/root/.aduna
  activemq:
    image: laus.fzi.de:8201/streampipes/activemq
    ports:
      - "61616:61616"
      - "61614:61614"
  couchdb:
    image: couchdb
    ports:
      - "5984:5984"
    volumes:
      - /home/riemer/swarm/config/couchdb/data:/usr/local/var/lib/couchdb
  nginx:
    image: laus.fzi.de:8201/streampipes/nginx
    ports:
      - "80:80"
    volumes:
      - /home/riemer/swarm/config/nginx:/etc/nginx/conf.d
  flink-samples:
    image: laus.fzi.de:8201/streampipes/semantic-epa-flink-samples
#    ports:
#      - "8094:8094"
    volumes:
      - /home/riemer/swarm/config:/root/.streampipes
  sources:
    image: laus.fzi.de:8201/streampipes/semantic-epa-sources-samples
    ports:
      - "8089:8089"
    volumes:
      - /home/riemer/swarm/config:/root/.streampipes
  esper:
    image: laus.fzi.de:8201/streampipes/semantic-epa-esper
    ports:
      - "8090:8090"
    volumes:
      - /home/riemer/swarm/config:/root/.streampipes
  actions:
    image: laus.fzi.de:8201/streampipes/semantic-epa-actions-samples
    ports:
      - "8091:8091"
    volumes:
      - /home/riemer/swarm/config:/root/.streampipes
  flink-samples:
    image: laus.fzi.de:8201/streampipes/semantic-epa-flink-samples
    ports:
      - "8094:8094"
    volumes:
      - /home/riemer/swarm/config:/root/.streampipes
  mnist:
    image: laus.fzi.de:8201/streampipes/semantic-epa-sources-mnist
    ports:
      - "8078:8078"
    volumes:
      - /home/riemer/swarm/config:/root/.streampipes
  ml:
    image: laus.fzi.de:8201/streampipes/semantic-epa-flink-samples-ml
    ports:
      - "8087:8087"
    volumes:
      - /home/riemer/swarm/config:/root/.streampipes
  kafka-web-console:
    image: hwestphal/kafka-web-console
    ports:
      - "9000:9000"
    volumes:
      - /home/riemer/swarm/config:/data hwestphal/kafka-web-console
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - "9001:9000"
    environment:
      ZK_HOST: "141.21.9.88:2181"
      APPLICATION_SECRET: "letmein"
## working configuration for flink
  jobmanager:
    image: laus.fzi.de:8201/streampipes/flink
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - /home/riemer/swarm/config/flink:/opt/flink/conf
  taskmanager:
    image: laus.fzi.de:8201/streampipes/flink
    command: taskmanager
    volumes:
      - /home/riemer/swarm/config/flink:/opt/flink/conf


