version: "2"
services:
  processors-python:
    image: ipe-wim-gitlab.fzi.de:5000/streampipes/streampipes-python-wrapper:${SP_PE_VERSION}
    depends_on:
      - "consul"
#    ports:
#      - "8098:8090"
    environment:
      - SP_ICON_HOST=${SP_ICON_HOST}
    networks:
      spnet:
