name: Build and Deploy Extensions

on:
  push:
    branches:
      - dev
jobs:
  build-and-push-to-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Extensions with Maven
        run: mvn clean package javadoc:aggregate -U -DskipTests -Denforcer.skip
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
      - name: Extract current snapshot version
        run: echo "::set-env name=MVN_VERSION::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
      - name: Build and Push Docker Image pipeline-elements-all-jvm
        run: |
          echo "${{env.MVN_VERSION}}"
          COMPONENT_NAME=pipeline-elements-all-jvm
          IMAGE_NAME=apachestreampipes/$COMPONENT_NAME:$MVN_VERSION
          echo BIMAGE_NAME=$IMAGE_NAME
          docker build --pull -t $IMAGE_NAME ./streampipes-$COMPONENT_NAME/
          docker push $IMAGE_NAME
